### PR TITLE
Sams post

### PR DESCRIPTION
**Pull request by SamLau95**
@brownhead Hey! I don't have write access to KA repos anymore so I made a PR from my own fork. This has William's commit too for the upcoming post. We'll merge this in on Aug. 31.

### CODE REVIEW

**Comment by wchargin** [comment]
Builds fine for me.

**Comment by wchargin** [comment]
@brownhead Any idea why the checks are consistently failing?

**Comment by sophiebits** [comment]
I think this will fail on any pull request since Travis won't provide the key:

https://github.com/Khan/engblog/blob/5350c96d7690388366756e627b3537ab3973ba36/.travis.yml#L7

You can do something like this to check:

https://github.com/facebook/react/blob/f641f29db0a16edfeb8ec666e1db51abbdc6f1a8/.travis.yml#L22

**Comment by itsjohncs** [comment]
Awesome! I'll pull this in around lunch time today, unless you'd like me to pull it in sooner/later @SamLau95.

I opened up an issue (#36) to take care of the incorrectly failing build. Sorry it was giving everyone trouble :(.

**Comment by wchargin** [comment]
no trouble @brownhead!

**Pull request merged**
