### PR TITLE
optimize images for filesize losslessly

### PR DESCRIPTION
**Pull request by mroth**
overall this cuts out about ~30% of our image load, with some files being cut in size more than half.

not a massive deal, but why not? it's free!

Test Plan: :eyes:

### CODE REVIEW

**Comment by mroth** [comment]
Not doing this in Phabricator because there is no code and this workflow makes more sense for stuff like this!

**Comment by sophiebits** [comment]
(What did you run?)

**Comment by itsjohncs** [comment]
The travis failures are just cause of #36, nothing to worry about.

**Comment by mroth** [comment]
@spicyj just image_optim which bundles a slew of optimizers.  (I have an automated tool mroth/pullcrusher that does that as a single step, but I didn't use it here since I thought I was going to use Phabricator at first.)

**Comment by itsjohncs** [comment]
Sweet! This looks good. Travis won't publish to the blog if the tests fail, and I suspect they won't anyways, so going to merge this in despite an angry Travis.

Thanks @mroth!

**Comment by csilvers** [comment]
btw, we have a cron job that does this automatically, every week, in the webapp repo.  It might be worthwhile to extend that to other repos as well.  See https://jenkins.khanacademy.org/job/webapp-maintenance/, which eventually runs (the by now misnamed) deploy/pngcrush.py.

**Comment by benkomalo** [comment]
whoa. I didn't know about that weekly job. that's interesting.

mobile production process is still pretty nascent, but we should keep tabs on all the things webapp et al are doing @nefaurk

**Pull request merged**
