### PR TITLE
npm audit fix security vulnerabilities

### PR DESCRIPTION
**Pull request by drosile**
Automated fixes from npm audit fix

### CODE REVIEW

**Comment by drosile** [comment]
i think the travisci integration is broken. it says `iv undefined` -- it might be missing secrets or something.

**Comment by dangoor** [comment]
Unfortunately, broken travis also means no builds of the blog itself

**Comment by csilvers** [comment]
Did you test that we can still rebuild the blog after the update?  I'd love to have at least some cursory checks this upgrade doesn't break anything.

**Comment by drosile** [comment]
ah, yes, i should have mentioned. i did `make deps` & `make serve` after these changes and it looked fine to me

**Pull request merged**
